### ISSUE TITLE
New still does not work on 0.5.5

### ISSUE THREAD

**Issue by kkneutgen** [satokaz/vscode-memo-life-for-you#58]
On my linux-system the bug #55 still exists with memo version 0.5.5.

```
[Extension Host] Unhandled Rejection:  Error: EISDIR: illegal operation on a directory, read
	at Object.readSync (fs.js:506:3)
	at tryReadSync (fs.js:331:20)
	at Object.readFileSync (fs.js:368:19)
	at Object.fs.readFileSync (electron/js2c/asar.js:542:40)
	at memoTemplate (/home/me/.vscode/extensions/satokaz.vscode-memo-life-for-you-0.5.5/dist/extension.js:11:37604)
	at /home/me/.vscode/extensions/satokaz.vscode-memo-life-for-you-0.5.5/dist/extension.js:11:35435
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

I had to create a template-file and set the path via memotemplate = "path/to/my/templatefile".

**Comment by satokaz** [comment]
Thank you for reporting!  
I will check it.

**Comment by satokaz** [comment]
@kkneutgen 

Insufficient measures were taken when memotemplate was not set.
Thanks for the report.

I have published a new version.

Thanks,
Kazuyuki

**Comment by kkneutgen** [comment]
That's it, thank you!
